version: '3.6'
services:
  web:
    image: nginx:alpine
    ports:
      - "1001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - notes
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - notes
    depends_on:
      - web
      - database
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - notes_data:/var/lib/mysql
    networks:
      - notes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "2000:80"
    depends_on:
      - database
    links:
      - "database:db"
    networks:
      - notes
networks:
  notes:
    name: notes
    driver: bridge
volumes:
  notes_data:
    driver: local
